security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
  providers:
    ums:
      memory:
        users:
          user:  { password: '%env(USER_PASSWORD)%', roles: [ 'ROLE_USER' ] }
          admin: { password: '%env(ADMIN_PASSWORD)%', roles: [ 'ROLE_ADMIN' ] }
  firewalls:
    api:
      pattern:  ^/api
      anonymous: ~
      http_basic:
        realm: Secured Area
  access_control:
  - { path: ^/api/ums, roles: ROLE_ADMIN }